{
	"name": "cd",
	"on": {
		"push": {
			"tags": [
				"[a-z]+-[0-9]+.[0-9]+.[0-9]+"
			]
		}
	},
	"jobs": {
		"publish": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npm run build" },
				{
					"env": {
						"NODE_AUTH_TOKEN": "${{ secrets.NPM_TOKEN }}"
					},
					"run": "echo ${{ github.ref_name }}"
				}
			]
		}
	}
}
