{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["dev"]
		}
	},
	"jobs": {
		"push": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "ref": "dev" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "git config user.name \"GitHub Actions\" && git config user.email \"actions@users.noreply.github.com\"" },

				{ "run": "npx turbo run build" },

				{ "run": "npm pkg delete workspaces" },
				{ "run": "sed -i \"/^dist$/d\" .gitignore" },

				{ "run": "git fetch origin dev:dev" },
				{ "run": "git reset --hard dev" },

				{ "run": "git add --all" },
				{ "run": "git -c author.name=brianjenkins94 -c author.email=brianjenkins94@users.noreply.github.com -c committer.name=GitHub -c committer.email=noreply@github.com commit -m \"Updated build artifacts\"" },
				{ "run": "git reset --hard" },
				{ "run": "git clean -f -d" },
				{ "run": "git checkout dev" },
				{ "run": "git reset --hard origin/dev" },
				{ "run": "git fetch origin main:refs/remotes/origin/main" },
				{ "run": "git push --force-with-lease origin HEAD:refs/heads/main" }
			]
		}
	}
}
