{
	"name": "ci",
	"on": {
		"push": {
			"branches": [
				"main"
			]
		}
	},
	"jobs": {
		"build": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
        {
          "uses": "actions/setup-node@v2",
          "with": {
            "node-version": 18
          }
        },
				{
					"run": "npm install"
				},
				{
					"run": "npm run build"
				}
			]
		},
    "lint": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
        {
          "uses": "actions/setup-node@v2",
          "with": {
            "node-version": 18
          }
        },
				{
					"run": "npm install"
				},
				{
					"run": "npm run lint"
				}
			]
		},
		"test": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
        {
          "uses": "actions/setup-node@v2",
          "with": {
            "node-version": 18
          }
        },
				{
					"run": "npm install"
				},
				{
					"run": "npm run test"
				}
			]
		},
		"publish": {
			"runs-on": "ubuntu-latest",
			"needs": ["lint", "build", "test"],
			"env": {
				"NODE_AUTH_TOKEN": "${{ secrets.NPM_TOKEN }}"
			},
			"steps": [
				{
					"uses": "actions/checkout@v2"
				},
        {
          "uses": "actions/setup-node@v2",
          "with": {
            "node-version": 18
          }
        },
				{
					"run": "npm build"
				},
				{
					"run": "npm publish"
				}
			]
		}
	}
}
