{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["main"]
		}
	},
	"jobs": {
		"build-lint-test": {
			"runs-on": "ubuntu-latest",
			"strategy": {
				"matrix": {
					"script": ["build", "lint", "test"]
				}
			},
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npm run ${{ matrix.script }}" }
			]
		},
		"changes": {
			"runs-on": "ubuntu-latest",
			"needs": ["build-lint-test"],
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{
					"id": "enumerate",
					"run": "echo PACKAGES=\"$(npm run changes --silent)\" >> $GITHUB_OUTPUT"
				},
				{
					"if": "steps.enumerate.outputs.PACKAGES != '{}'",
					"uses": "dorny/paths-filter@v2",
					"id": "filter",
					"with": {
						"filters": "${{ steps.enumerate.outputs.PACKAGES }}"
					}
				}
			],
			"outputs": {
				"packages": "${{ steps.filter.outputs.changes }}"
			}
		},
		"release": {
			"if": "needs.changes.outputs.packages != '' && needs.changes.outputs.packages != '[]'",
			"runs-on": "ubuntu-latest",
			"needs": ["changes"],
			"strategy": {
				"matrix": {
					"package": "${{ fromJSON(needs.changes.outputs.packages) }}"
				}
			},
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{
					"id": "version",
					"run": "echo VERSION=$(npm pkg get version) >> $GITHUB_OUTPUT"
				},
				{
					"uses": "softprops/action-gh-release@v1",
					"with": {
						"tag_name": "${{ matrix.package }}-${{ steps.version.outputs.VERSION }}",
						"prerelease": true
					},
					"env": {
						"GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
					}
				}
			],
			"outputs": {
				"package": "${{ matrix.package }}"
			}
		},
		"publish": {
			"runs-on": "ubuntu-latest",
			"needs": ["release"],
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npm run build" },
				{
					"env": {
						"NODE_AUTH_TOKEN": "${{ secrets.NPM_TOKEN }}"
					},
					"working-directory": "${{ needs.release.outputs.package }}",
					"run": "# npm run publish"
				}
			]
		}
	}
}
