{
	"name": "ci",
	"on": {
		"push": {
			"branches": [
				"main"
			]
		}
	},
	"jobs": {
		"build": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v3"
				},
				{
					"uses": "actions/setup-node@v3",
					"with": {
						"node-version": 18
					}
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run build"
				}
			]
		},
		"lint": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v3"
				},
				{
					"uses": "actions/setup-node@v3",
					"with": {
						"node-version": 18
					}
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run lint"
				}
			]
		},
		"test": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"uses": "actions/checkout@v3"
				},
				{
					"uses": "actions/setup-node@v3",
					"with": {
						"node-version": 18
					}
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm run test"
				}
			]
		},
		"changes": {
			"runs-on": "ubuntu-latest",
			"needs": ["build", "lint", "test"],
			"steps": [
				{
					"uses": "actions/checkout@v3"
				},
				{
					"uses": "actions/setup-node@v3",
					"with": {
						"node-version": 18
					}
				},
				{
					"run": "npm install"
				},
				{
					"run": "echo PACKAGES=[$(find . -mindepth 2 -name \"package.json\" -not -path \"*/.*\" -not -path \"*/node_modules/**\" | sed -z \"s/^/\\\"/;s/\\n$/\\\"/;s/\\n/\\\",\\\"/g\")] >> $GITHUB_OUTPUT"
				}
			]
		},
		"release": {
			"runs-on": "ubuntu-latest",
			"needs": ["changes"],
			"strategy": {
				"matrix": {
					"packages": "${{ fromJSON(needs.changes.outputs.PACKAGES) }}"
				}
			},
			"steps": [
				{
					"uses": "softprops/action-gh-release@v1",
					"env": {
						"GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
					},
					"with": {
						"name": "Release v${{ needs.check_if_version_upgraded.outputs.to_version }}",
						"tag_name": "v${{ needs.check_if_version_upgraded.outputs.to_version }}",
						"target_commitish": "${{ github.head_ref || github.ref }}"
					}
				}
			]
		},
		"publish": {
			"runs-on": "ubuntu-latest",
			"needs": ["changes", "release"],
			"strategy": {
				"matrix": {
					"packages": "${{ fromJSON(needs.changes.outputs.PACKAGES) }}"
				}
			},
			"steps": [
				{
					"uses": "actions/checkout@v3"
				},
				{
					"uses": "actions/setup-node@v3",
					"with": {
						"node-version": 18
					}
				},
				{
					"run": "npm install"
				},
				{
					"run": "npm build"
				},
				{
					"run": "npm publish",
					"env": {
						"NODE_AUTH_TOKEN": "${{ secrets.NPM_TOKEN }}",
						"VERSION": "${{ needs.check_if_version_upgraded.outputs.to_version }}"
					}
				}
			]
		}
	}
}
