{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["dev"]
		}
	},
	"jobs": {
		"push": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "ref": "dev" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "git config user.name \"GitHub Actions\" && git config user.email \"actions@users.noreply.github.com\"" },

				{ "run": "npx turbo run build" },

				{ "run": "npm pkg delete workspaces" },
				{ "run": "sed -i \"/^dist$/d\" .gitignore" },

				{
					"uses": "peter-evans/create-pull-request@v4",
					"with": {
						"title": "Automated build",
						"base": "dev"
						"branch": "main",
						"commit-message": "Updated build artifacts"
					}
				}
			]
		}
	}
}
