{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["main"]
		}
	},
	"jobs": {
		"build": {
			"runs-on": "ubuntu-latest",
			"strategy": {
				"matrix": {
					"script": ["build", "lint", "test"]
				},
			},
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "run": "npm install" },
				{ "run": "npm run ${{ matrix.script }}" }
			]
		},
		"changes": {
			"runs-on": "ubuntu-latest",
			"needs": ["build"],
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{
					"uses": "dorny/paths-filter@v2",
					"id": "filter",
					"with": {
						"filters": "{\"apps/web\":\"apps/web/**\"}"
					}
				}
			],
			"outputs": {
				"packages": "${{ steps.packages.outputs.PACKAGES }}"
			}
		},
		"release": {
			"if": "${{ needs.changes.outputs.packages != '' }}",
			"runs-on": "ubuntu-latest",
			"needs": ["changes"],
			"strategy": {
				"matrix": {
					"package": "${{ fromJSON(needs.changes.outputs.packages) }}"
				}
			},
			"steps": [
				{
					"run": "echo ${{ matrix.package }}"
				}
			]
		}
	}
}
