{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["main"]
		}
	},
	"jobs": {
		"enumerate": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{
					"id": "enumerate",
					"run": "echo PACKAGES=\"[$(find . -name \"package.json\" -not -path \"*/.*\" -not -path \"*/node_modules/**\" -exec dirname {} \\; | sed -z \"s/^/\\\"/;s/\\n$/\\\"/;s/\\n/\\\",\\\"/g\")]\" >> $GITHUB_OUTPUT"
				},
			],
			"outputs": {
				"packages": "${{ steps.enumerate.outputs.PACKAGES }}"
			}
		},
		"install": {
			"runs-on": "ubuntu-latest",
			"needs": ["enumerate"],
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{
					"uses": "bahmutov/npm-install@v1",
					"with": {
						"working-directory": "${{ join(fromJSON(needs.enumerate.outputs.packages), '\n') }}",
						"useLockFile": false
					}
				}
			]
		},
		"build": {
			"runs-on": "ubuntu-latest",
			"needs": ["enumerate", "install"],
			"strategy": {
				"matrix": {
					"script": ["build", "lint", "test"]
				},
			},
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{
					"uses": "bahmutov/npm-install@v1",
					"with": {
						"working-directory": "${{ join(fromJSON(needs.enumerate.outputs.packages), '\n') }}",
						"useLockFile": false
					}
				}
				{ "run": "npm run ${{ matrix.script }}" }
			]
		},
		"changes": {
			"runs-on": "ubuntu-latest",
			"needs": ["build"],
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{
					"id": "enumerate",
					"run": "echo PACKAGES=\"{\\\"apps/web\\\":\\\"apps/web/**\\\"}\" >> $GITHUB_OUTPUT"
				},
				{
					"uses": "dorny/paths-filter@v2",
					"id": "filter",
					"with": {
						"filters": "${{ steps.enumerate.outputs.PACKAGES }}"
					}
				}
			],
			"outputs": {
				"packages": "${{ steps.filter.outputs.changes }}"
			}
		},
		"release": {
			"if": "${{ needs.changes.outputs.packages != '' && needs.changes.outputs.packages != '[]' }}",
			"runs-on": "ubuntu-latest",
			"needs": ["enumerate", "changes"],
			"strategy": {
				"matrix": {
					"package": "${{ fromJSON(needs.changes.outputs.packages) }}"
				}
			},
			"env": {
				"NODE_ENV": "production"
			},
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{
					"uses": "bahmutov/npm-install@v1",
					"with": {
						"working-directory": "${{ join(fromJSON(needs.enumerate.outputs.packages), '\n') }}",
						"useLockFile": false
					}
				},
				{
					"run": "echo ${{ matrix.package }}"
				}
			],
			"outputs": {
				"package": "${{ matrix.package }}"
			}
		},
		"publish": {
			"runs-on": "ubuntu-latest",
			"needs": ["enumerate", "release"],
			"env": {
				"NODE_ENV": "production"
			},
			"steps": [
				{ "uses": "actions/checkout@v3" },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{
					"uses": "bahmutov/npm-install@v1",
					"with": {
						"working-directory": "${{ join(fromJSON(needs.enumerate.outputs.packages), '\n') }}",
						"useLockFile": false
					}
				},
				{ "run": "npm run build" },
				{
					"env": {
						"NODE_AUTH_TOKEN": "${{ secrets.NPM_TOKEN }}"
					},
					"working-directory": "${{ needs.release.outputs.package }}",
					"run": "npm run publish"
				}
			]
		}
	}
}
