{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["dev"]
		}
	},
	"jobs": {
		"push": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "actions/checkout@v3", "with": { "path": "dev", "ref": "dev" } },
				{ "uses": "actions/checkout@v3", "with": { "path": "main", "ref": "main" } },

				{ "run": "cd dev" },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npx turbo run build" },
				{ "run": "npm pkg delete workspaces" },
				{ "run": "sed -i \"/^dist$/d\" .gitignore" },

				{ "run": "cd .." },
				{ "run": "rsync --archive --exclude=\".*/\" dev main" },

				{ "run": "cd main" },
				{
					"uses": "peter-evans/create-pull-request@v4",
					"with": {
						"title": "Automated build",
						"commit-message": "Updated build artifacts"
					}
				}
			]
		}
	}
}
