{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["dev"]
		}
	},
	"jobs": {
		"cache": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "ref": "dev" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } }
			]
		},
		"build-lint-test": {
			"runs-on": "ubuntu-latest",
			"needs": ["cache"],
			"strategy": {
				"matrix": {
					"script": ["build", "lint", "test"]
				}
			},
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "ref": "dev" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npx turbo run ${{ matrix.script }}" }
			]
		},
		"create-pull-request": {
			"runs-on": "ubuntu-latest",
			"needs": ["build-lint-test"],
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "path": "dev", "ref": "dev" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },

				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false, "working-directory": "dev" } },
				{ "run": "npx turbo run build", "working-directory": "dev" },
				{ "run": "npm pkg delete workspaces", "working-directory": "dev" },
				{ "run": "sed -i \"/^dist$/d\" .gitignore", "working-directory": "dev" },

				{ "uses": "actions/checkout@v3", "with": { "path": "main", "ref": "main" } },
				{ "run": "rsync --delete --exclude=\".git/\" --recursive dev/ main" },

				{
					"uses": "peter-evans/create-pull-request@v4",
					"id": "cpr",
					"with": {
						"title": "Automated build",
						"commit-message": "Updated build artifacts",
						"delete-branch": true,
						"path": "main",
						"token": "${{ secrets.PAT }}"
					}
				},
				{
					"if": "steps.cpr.outputs.pull-request-operation == 'created'",
					"uses": "peter-evans/enable-pull-request-automerge@v2",
					"with": {
						"pull-request-number": "${{ steps.cpr.outputs.pull-request-number }}",
						"token": "${{ secrets.PAT }}"
					}
				}
			]
		}
	}
}
