{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["main"]
		}
	},
	"jobs": {
		"cache": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "ref": "main" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } }
			]
		},
		"build-lint-test": {
			"runs-on": "ubuntu-latest",
			"needs": ["cache"],
			"strategy": {
				"matrix": {
					"script": ["build", "lint", "test"]
				}
			},
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "ref": "main" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npx turbo run ${{ matrix.script }}" }
			]
		},
		"push": {
			"runs-on": "ubuntu-latest",
			"needs": ["build-lint-test"],
			"steps": [
				{ "uses": "actions/checkout@v3", "with": { "ref": "main" } },
				{ "uses": "actions/setup-node@v3", "with": { "node-version": 18 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npx turbo run build" },
				{ "run": "npm pkg delete workspaces" },
				{ "run": "sed -i \"/^dist$/d\" .gitignore" },
				{ "run": "git commit --all --allow-empty-message --author=\"github-actions-bot <support+actions@github.com>\"" },
				{ "run": "git checkout dist" },
				{ "run": "git merge main" },
				{ "run": "git push" }
			]
		}
	}
}
